/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import alien from "../../3D-assests/alien.glb"

export default function Alien({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(alien)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 0, 463.12]}>
              <mesh geometry={nodes['Box001_Material_#25_0'].geometry} material={materials.Material_25} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/alien.glb')
