/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import ninja from "../../3D-assests/ninja.glb";

export default function Ninja({ isWalking, convertedCameraRotation }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(ninja);
  const { actions } = useAnimations(animations, group);

  // const [ref, api] = useBox(() => ({
  //   mass: 1,
  //   rotation: [Math.PI / 2, 0, 0],
  //   position: [0, 0, 0],
  //   type: "Static",
  //   args: [1, 2, 1],
  // }));


  useEffect(() => {
      actions[isWalking].reset().fadeIn(0.5).play();
      return () => actions[isWalking].fadeOut(0.5);
  }, [actions, isWalking]);

  return (
    <group ref={group} dispose={null} 
    position={[0, -1, 0]}
    >
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          geometry={nodes.Ch24.geometry}
          material={materials.Ch24_Body}
          skeleton={nodes.Ch24.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload(ninja);
