/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import ninja from "../../3D-assests/ninja.glb"

export default function Ninja({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(ninja)
  const { actions } = useAnimations(animations, group)

  useEffect( () => {
    actions.walking.reset().fadeIn(0.5).play()
    return () => actions.walking.fadeout(0.5)
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh geometry={nodes.Ch24.geometry} material={materials.Ch24_Body} skeleton={nodes.Ch24.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload(ninja)
